# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and run test extras

on:
  push:
    branches: [ "beta", "master" ]
  #pull_requests
  #  branches: [ "master", "develop", "beta" ]
  # Allow running manually from Actions tab
  workflow_dispatch:

env:
  SKIP_DEAP: 1

jobs:
  test_extras: # On stable branches, run extended tests

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Finish all tests even if one fails
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
        python-version: [3.7, 3.8, 3.9, '3.10']
        extra-tests:
        - "algorithms"
        - "algorithmsb"
        - "report"
        - "reportb"
        - "objects"
        - "tools"
        - "iotest"
        - "drivers"
        - "optimize"
        - "construction"
        - "extras"
        # - "mpi" # Fails in GitHub Actions, passes locally but doesn't terminate threads properly

    steps:
    - uses: actions/checkout@v2
    - name: Set up installation environment
      run: |
        ./.github/ci-scripts/before_install.sh
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}-${{ hashFiles('**/*requirements.txt') }}
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        # Installing with -e to keep installation local (for NOSE_NOPATH)
        # but still compile Cython extensions
        python -m pip install -e .[testing]
        python setup.py build_ext --inplace
    - name: Run test_packages Ubuntu ${{ matrix.extra-tests }}
      if: ${{matrix.os == 'ubuntu-20.04'}}
      env:
        PYTESTS: ${{ matrix.extra-tests }}
      run: |
        python -Ic "import pygsti; print(pygsti.__version__); print(pygsti.__path__)"
        echo "pytests: $PYTESTS"
        python -m pytest -n auto  $PYTESTS
    - name: Run test_packages Windows ${{ matrix.extra-tests }}
      if: ${{matrix.os == 'windows-2019'}}
      env:
        PYTESTS: ${{ matrix.extra-tests }}
      run: |
        python -Ic "import pygsti; print(pygsti.__version__); print(pygsti.__path__)"
        echo "pytest: $Env:PYTESTS"
        python -m pytest -n auto $Env:PYTESTS
    - name: Run test_packages MacOS ${{ matrix.extra-tests }}
      if: ${{matrix.os == 'macos-11'}}
      env:
        PYTESTS: ${{ matrix.extra-tests }}
      run: |
        python -Ic "import pygsti; print(pygsti.__version__); print(pygsti.__path__)"
        echo "pytests: $PYTESTS"
        python -m pytest -n auto  $PYTESTS



